# Generated by Django 2.0.5 on 2019-04-05 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190405_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='register_code')),
                ('status', models.BooleanField(default=False, help_text='1: use, 2: not use', verbose_name='register_code_statud')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '注册码',
                'verbose_name_plural': '注册码',
            },
        ),
    ]
