# Generated by Django 2.0.5 on 2019-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20190327_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='lld',
            field=models.BooleanField(default=1, help_text='为0表示不再出现', verbose_name='凉凉度'),
        ),
    ]
