# Generated by Django 2.0.5 on 2019-03-27 22:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0003_auto_20190327_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户系统通知记录表',
                'verbose_name_plural': '用户系统通知记录表',
            },
        ),
        migrations.RemoveField(
            model_name='notice',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='wish',
        ),
        migrations.AddField(
            model_name='notice',
            name='action_id',
            field=models.IntegerField(default=0, help_text='action 为1 评论ID， 2 点赞ID', verbose_name='内容'),
        ),
    ]
