# Generated by Django 2.0.5 on 2019-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20190327_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='action_id',
            field=models.IntegerField(default=0, help_text='action 为1 评论ID， 2 点赞ID', verbose_name='行为id'),
        ),
    ]
