# Generated by Django 2.0.5 on 2019-03-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20190327_1655'),
        ('user_operation', '0005_auto_20190328_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='wish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wish.Wish', verbose_name='动态'),
        ),
    ]
