# Generated by Django 2.0.5 on 2019-03-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_message_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.CharField(default='[]', help_text='最多30字', max_length=2000, verbose_name='内容'),
        ),
    ]
