# Generated by Django 2.0.5 on 2019-03-31 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0008_auto_20190330_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user_receive', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='short_messages_receive', to=settings.AUTH_USER_MODEL, verbose_name='接受信息用户')),
                ('user_send', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='short_messages_send', to=settings.AUTH_USER_MODEL, verbose_name='发送信息用户')),
            ],
            options={
                'verbose_name': '信息表',
                'verbose_name_plural': '信息表',
            },
        ),
        migrations.CreateModel(
            name='UserShortMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息记录表',
                'verbose_name_plural': '用户信息记录表',
            },
        ),
    ]
