# Generated by Django 2.0.5 on 2019-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0009_shortmessages_usershortmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='父级id'),
        ),
    ]
